name: tweet-last-post-from-feed
on:
  push:
    branches: master
  schedule:
    - cron: '0 * * * *'
  watch:
    types: [started]
jobs:
  tweet-last-post-from-feed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - run: pip install -r requirements.txt
      - name: Update
        uses: ./
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_OAUTH_TOKEN: ${{ secrets.TWITTER_OAUTH_TOKEN }}
          TWITTER_OAUTH_SECRET: ${{ secrets.TWITTER_OAUTH_SECRET }}
          FEED_URL: ${{ secrets.FEED_URL }}
  